gateway:
  id: G-199
  name: 桃園捷運 車組 199
  location: 桃園捷運
  poll_interval_ms: 1000
network:
  gateway_mqtt:
    enabled: true
    broker_host: 220.133.144.73
    broker_port: 1883
    topic_prefix: "TYMC/AIR/199/#"
    clean_session: true
  cloud_mqtt:
    enabled: true
    broker_host: 220.133.144.73
    broker_port: 1883
    username: ""
    password: ""
    client_id: "GW-TAU-199-CLOUD-DEV"
    cloud_topic_prefix: "MQT/TRA/OTR/TRC/199"
    qos: 1
    reconnect_delay_sec: 5
    keepalive: 20
    clean_session: true
  ipc_socket_path: /tmp/hvac_ipc.sock
database:
  db_path: gateway.db
  batch_size: 100
  batch_flush_sec: 5
equipments:
- id: "1"
  protocol: MQTT
  name: 1車端點1
  ip: 192.168.16.91
- id: "2"
  protocol: MQTT
  name: 1車端點2
  ip: 192.168.16.92
- id: "3"
  protocol: MQTT
  name: 2車端點1
  ip: 192.168.16.93
- id: "4"
  protocol: MQTT
  name: 2車端點2
  ip: 192.168.16.94
- id: "5"
  protocol: MQTT
  name: 3車端點1
  ip: 192.168.16.95
- id: "6"
  protocol: MQTT
  name: 3車端點2
  ip: 192.168.16.96
- id: "7"
  protocol: MQTT
  name: 4車端點1
  ip: 192.168.16.97
- id: "8"
  protocol: MQTT
  name: 4車端點2
  ip: 192.168.16.98
