gateway:
  id: G-101
  name: 桃園捷運 車組 101
  location: 桃園捷運
  poll_interval_ms: 1000
network:
  mqtt:
    enabled: true
    broker_host: 220.133.144.73
    broker_port: 1883
    topic_prefix: "TYMC/AIR/101/#"
  cloud_mqtt:
    enabled: true
    broker_host: 220.133.144.73
    broker_port: 1883
    username: ""
    password: ""
    client_id: "GW-TAU-01-CLOUD"
    publish_topic_prefix: "TYMC/CLOUD/101"
    qos: 0
    reconnect_delay_sec: 5
  ipc_socket_path: /tmp/hvac_ipc.sock
database:
  db_path: gateway.db
  batch_size: 100
  batch_flush_sec: 5
equipments:
- id: "1"
  protocol: MQTT
  name: 1車端點1
  ip: 192.168.16.91
  registers:
  - code: D40001
    name: 主控制模式 (DI 1/2)
    address: 40001
    type: INT16
    scale: 1.0
    unit: N/A
    sensor_type: REAL_TIME
    value: 2
  - code: D40009
    name: 氨氣感測器值
    address: 40009
    type: INT16
    scale: 1.0
    unit: ppm
    sensor_type: REAL_TIME
    value: 0
  - code: D40010
    name: 擋板運行模式選擇
    address: 40010
    type: INT16
    scale: 1.0
    unit: N/A
    sensor_type: REAL_TIME
    value: 0
  - code: D40011
    name: 新鮮空氣擋板位置 (回饋)
    address: 40011
    type: INT16
    scale: 1.0
    unit: '%'
    sensor_type: REAL_TIME
    value: 0
  - code: D40012
    name: 緊急空氣擋板位置 (回饋)
    address: 40012
    type: INT16
    scale: 1.0
    unit: N/A
    sensor_type: REAL_TIME
    value: 0
  - code: D40013
    name: 回風擋板位置 (回饋)
    address: 40013
    type: INT16
    scale: 1.0
    unit: N/A
    sensor_type: REAL_TIME
    value: 0
  - code: D40014
    name: 排氣擋板位置 (回饋)
    address: 40014
    type: INT16
    scale: 1.0
    unit: N/A
    sensor_type: REAL_TIME
    value: 0
- id: "2"
  protocol: MQTT
  name: 1車端點2
  ip: 192.168.16.92
  registers:
  - code: D40001
    name: 主控制模式 (DI 1/2)
    address: 40001
    type: INT16
    scale: 1.0
    unit: N/A
    sensor_type: REAL_TIME
    value: 2
  - code: D40009
    name: 氨氣感測器值
    address: 40009
    type: INT16
    scale: 1.0
    unit: ppm
    sensor_type: REAL_TIME
    value: 0
  - code: D40010
    name: 擋板運行模式選擇
    address: 40010
    type: INT16
    scale: 1.0
    unit: N/A
    sensor_type: REAL_TIME
    value: 0
  - code: D40011
    name: 新鮮空氣擋板位置 (回饋)
    address: 40011
    type: INT16
    scale: 1.0
    unit: '%'
    sensor_type: REAL_TIME
    value: 0
  - code: D40012
    name: 緊急空氣擋板位置 (回饋)
    address: 40012
    type: INT16
    scale: 1.0
    unit: N/A
    sensor_type: REAL_TIME
    value: 0
  - code: D40013
    name: 回風擋板位置 (回饋)
    address: 40013
    type: INT16
    scale: 1.0
    unit: N/A
    sensor_type: REAL_TIME
    value: 0
  - code: D40014
    name: 排氣擋板位置 (回饋)
    address: 40014
    type: INT16
    scale: 1.0
    unit: N/A
    sensor_type: REAL_TIME
    value: 0
- id: "3"
  protocol: MQTT
  name: 2車端點1
  ip: 192.168.16.93
  registers:
  - code: D40001
    name: 主控制模式 (DI 1/2)
    address: 40001
    type: INT16
    scale: 1.0
    unit: N/A
    sensor_type: REAL_TIME
    value: 2
  - code: D40009
    name: 氨氣感測器值
    address: 40009
    type: INT16
    scale: 1.0
    unit: ppm
    sensor_type: REAL_TIME
    value: 0
  - code: D40010
    name: 擋板運行模式選擇
    address: 40010
    type: INT16
    scale: 1.0
    unit: N/A
    sensor_type: REAL_TIME
    value: 0
  - code: D40011
    name: 新鮮空氣擋板位置 (回饋)
    address: 40011
    type: INT16
    scale: 1.0
    unit: '%'
    sensor_type: REAL_TIME
    value: 0
  - code: D40012
    name: 緊急空氣擋板位置 (回饋)
    address: 40012
    type: INT16
    scale: 1.0
    unit: N/A
    sensor_type: REAL_TIME
    value: 0
  - code: D40013
    name: 回風擋板位置 (回饋)
    address: 40013
    type: INT16
    scale: 1.0
    unit: N/A
    sensor_type: REAL_TIME
    value: 0
  - code: D40014
    name: 排氣擋板位置 (回饋)
    address: 40014
    type: INT16
    scale: 1.0
    unit: N/A
    sensor_type: REAL_TIME
    value: 0
- id: "4"
  protocol: MQTT
  name: 2車端點2
  ip: 192.168.16.94
  registers:
  - code: D40001
    name: 主控制模式 (DI 1/2)
    address: 40001
    type: INT16
    scale: 1.0
    unit: N/A
    sensor_type: REAL_TIME
    value: 2
  - code: D40002
    name: 數位輸入狀態 (DI3-DI 16)
    address: 40002
    type: INT16
    scale: 1.0
    unit: N/A
    sensor_type: REAL_TIME
    value: 3710
  - code: D40010
    name: 擋板運行模式選擇
    address: 40010
    type: INT16
    scale: 1.0
    unit: N/A
    sensor_type: REAL_TIME
    value: 0
  - code: D40011
    name: 新鮮空氣擋板位置 (回饋)
    address: 40011
    type: INT16
    scale: 1.0
    unit: '%'
    sensor_type: REAL_TIME
    value: 0
  - code: D40012
    name: 緊急空氣擋板位置 (回饋)
    address: 40012
    type: INT16
    scale: 1.0
    unit: N/A
    sensor_type: REAL_TIME
    value: 0
  - code: D40013
    name: 回風擋板位置 (回饋)
    address: 40013
    type: INT16
    scale: 1.0
    unit: N/A
    sensor_type: REAL_TIME
    value: 0
  - code: D40014
    name: 排氣擋板位置 (回饋)
    address: 40014
    type: INT16
    scale: 1.0
    unit: N/A
    sensor_type: REAL_TIME
    value: 0
  - code: D40009
    name: 氨氣感測器值
    address: 40009
    type: INT16
    scale: 1.0
    unit: ppm
    sensor_type: REAL_TIME
    value: 0
- id: "5"
  protocol: MQTT
  name: 3車端點1
  ip: 192.168.16.95
  registers:
  - code: D40001
    name: 主控制模式 (DI 1/2)
    address: 40001
    type: INT16
    scale: 1.0
    unit: N/A
    sensor_type: REAL_TIME
    value: 2
  - code: D40010
    name: 擋板運行模式選擇
    address: 40010
    type: INT16
    scale: 1.0
    unit: N/A
    sensor_type: REAL_TIME
    value: 0
  - code: D40011
    name: 新鮮空氣擋板位置 (回饋)
    address: 40011
    type: INT16
    scale: 1.0
    unit: '%'
    sensor_type: REAL_TIME
    value: 0
  - code: D40012
    name: 緊急空氣擋板位置 (回饋)
    address: 40012
    type: INT16
    scale: 1.0
    unit: N/A
    sensor_type: REAL_TIME
    value: 0
  - code: D40013
    name: 回風擋板位置 (回饋)
    address: 40013
    type: INT16
    scale: 1.0
    unit: N/A
    sensor_type: REAL_TIME
    value: 0
  - code: D40014
    name: 排氣擋板位置 (回饋)
    address: 40014
    type: INT16
    scale: 1.0
    unit: N/A
    sensor_type: REAL_TIME
    value: 0
  - code: D40009
    name: 氨氣感測器值
    address: 40009
    type: INT16
    scale: 1.0
    unit: ppm
    sensor_type: REAL_TIME
    value: 0
- id: "6"
  protocol: MQTT
  name: 3車端點2
  ip: 192.168.16.96
  registers:
  - code: D40001
    name: 主控制模式 (DI 1/2)
    address: 40001
    type: INT16
    scale: 1.0
    unit: N/A
    sensor_type: REAL_TIME
    value: 2
  - code: D40009
    name: 氨氣感測器值
    address: 40009
    type: INT16
    scale: 1.0
    unit: ppm
    sensor_type: REAL_TIME
    value: 0
  - code: D40010
    name: 擋板運行模式選擇
    address: 40010
    type: INT16
    scale: 1.0
    unit: N/A
    sensor_type: REAL_TIME
    value: 0
  - code: D40011
    name: 新鮮空氣擋板位置 (回饋)
    address: 40011
    type: INT16
    scale: 1.0
    unit: '%'
    sensor_type: REAL_TIME
    value: 0
  - code: D40012
    name: 緊急空氣擋板位置 (回饋)
    address: 40012
    type: INT16
    scale: 1.0
    unit: N/A
    sensor_type: REAL_TIME
    value: 0
  - code: D40013
    name: 回風擋板位置 (回饋)
    address: 40013
    type: INT16
    scale: 1.0
    unit: N/A
    sensor_type: REAL_TIME
    value: 0
  - code: D40014
    name: 排氣擋板位置 (回饋)
    address: 40014
    type: INT16
    scale: 1.0
    unit: N/A
    sensor_type: REAL_TIME
    value: 0
- id: "7"
  protocol: MQTT
  name: 4車端點1
  ip: 192.168.16.97
  registers:
  - code: D40001
    name: 主控制模式 (DI 1/2)
    address: 40001
    type: INT16
    scale: 1.0
    unit: N/A
    sensor_type: REAL_TIME
    value: 2
  - code: D40009
    name: 氨氣感測器值
    address: 40009
    type: INT16
    scale: 1.0
    unit: ppm
    sensor_type: REAL_TIME
    value: 0
  - code: D40010
    name: 擋板運行模式選擇
    address: 40010
    type: INT16
    scale: 1.0
    unit: N/A
    sensor_type: REAL_TIME
    value: 0
  - code: D40011
    name: 新鮮空氣擋板位置 (回饋)
    address: 40011
    type: INT16
    scale: 1.0
    unit: '%'
    sensor_type: REAL_TIME
    value: 0
  - code: D40012
    name: 緊急空氣擋板位置 (回饋)
    address: 40012
    type: INT16
    scale: 1.0
    unit: N/A
    sensor_type: REAL_TIME
    value: 0
  - code: D40013
    name: 回風擋板位置 (回饋)
    address: 40013
    type: INT16
    scale: 1.0
    unit: N/A
    sensor_type: REAL_TIME
    value: 0
  - code: D40014
    name: 排氣擋板位置 (回饋)
    address: 40014
    type: INT16
    scale: 1.0
    unit: N/A
    sensor_type: REAL_TIME
    value: 0
- id: "8"
  protocol: MQTT
  name: 4車端點2
  ip: 192.168.16.98
  registers:
  - code: D40001
    name: 主控制模式 (DI 1/2)
    address: 40001
    type: INT16
    scale: 1.0
    unit: N/A
    sensor_type: REAL_TIME
    value: 2
  - code: D40009
    name: 氨氣感測器值
    address: 40009
    type: INT16
    scale: 1.0
    unit: ppm
    sensor_type: REAL_TIME
    value: 0
  - code: D40010
    name: 擋板運行模式選擇
    address: 40010
    type: INT16
    scale: 1.0
    unit: N/A
    sensor_type: REAL_TIME
    value: 0
  - code: D40011
    name: 新鮮空氣擋板位置 (回饋)
    address: 40011
    type: INT16
    scale: 1.0
    unit: '%'
    sensor_type: REAL_TIME
    value: 0
  - code: D40012
    name: 緊急空氣擋板位置 (回饋)
    address: 40012
    type: INT16
    scale: 1.0
    unit: N/A
    sensor_type: REAL_TIME
    value: 0
  - code: D40013
    name: 回風擋板位置 (回饋)
    address: 40013
    type: INT16
    scale: 1.0
    unit: N/A
    sensor_type: REAL_TIME
    value: 0
  - code: D40014
    name: 排氣擋板位置 (回饋)
    address: 40014
    type: INT16
    scale: 1.0
    unit: N/A
    sensor_type: REAL_TIME
    value: 0
