/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AGActionButtonRenderer: typeof import('./components/AGActionButtonRenderer.vue')['default']
    AgGridView2: typeof import('./components/AgGridView2.vue')['default']
    AgPagination: typeof import('./components/AgPagination.vue')['default']
    AGTagCell: typeof import('./components/AGTagCell.vue')['default']
    BaseButton: typeof import('./components/BaseButton.vue')['default']
    BaseButtonGroup: typeof import('./components/BaseButtonGroup.vue')['default']
    BaseIcon: typeof import('./components/BaseIcon.vue')['default']
    BaseRangeSlider: typeof import('./components/BaseRangeSlider.vue')['default']
    BaseSwitch: typeof import('./components/BaseSwitch.vue')['default']
    Breadcrumb: typeof import('./components/Breadcrumb.vue')['default']
    DefaultActionCell: typeof import('./components/DefaultActionCell.vue')['default']
    ECLineChart: typeof import('./components/ECLineChart.vue')['default']
    ElAutocomplete: typeof import('element-plus/es')['ElAutocomplete']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCheckboxGroup: typeof import('element-plus/es')['ElCheckboxGroup']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDialogCustom: typeof import('./components/ElDialogCustom.vue')['default']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormCustom: typeof import('./components/ElFormCustom.vue')['default']
    ElFormFlex: typeof import('./components/ElFormFlex.vue')['default']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSearchCustom: typeof import('./components/ElSearchCustom.vue')['default']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTimeSelect: typeof import('element-plus/es')['ElTimeSelect']
    EndpointCard: typeof import('./components/EndpointCard.vue')['default']
    LoadingOverlay: typeof import('./components/LoadingOverlay.vue')['default']
    MapEditor: typeof import('./components/MapEditor.vue')['default']
    PageHeader: typeof import('./components/PageHeader.vue')['default']
    RoomBedMap: typeof import('./components/RoomBedMap.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StatsCard: typeof import('./components/StatsCard.vue')['default']
    SvgViewer: typeof import('./components/SvgViewer.vue')['default']
    TLAlertsContainer: typeof import('./components/TLAlertsContainer.vue')['default']
    TreeItem: typeof import('./components/TreeItem.vue')['default']
    TreeList: typeof import('./components/TreeList.vue')['default']
  }
}
